FROM node:14.13.1-stretch-slim

# Create app directory
WORKDIR /usr/src/app

# Path to binary jq (used by node-jq)
ENV JQ_PATH=/usr/bin/jq

# Man folders are required to install postgres-client without errors
RUN mkdir -p /usr/share/man/man1 /usr/share/man/man7

# Clone the skeleton project and install dependencies
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y git procps autoconf libtool make jq postgresql-client

EXPOSE 3000

