// Replaces next-plugin-preval: the original Next app used a webpack loader
// to run this same logic (parseStaticModels/getModelNavRoutes/getStaticQueries)
// at compile time and inject the result as a static module. Vite has no
// equivalent loader, so this runs as a plain pre-build/pre-dev script (see
// package.json's predev/prebuild) instead, writing its output to src/generated/
// and src/custom/queries/ - genuinely static files, imported normally by the
// app, not regenerated at runtime. Reads ZENDRO_DATA_MODELS exactly like the
// original did; swapping this for a runtime introspection query is a
// deliberate follow-up, not done here.
import { mkdir, writeFile } from 'fs/promises';
import { join } from 'path';
import { format } from 'prettier';

import { parseStaticModels } from '../src/build/models';
import { getModelNavRoutes } from '../src/build/routes';
import { getStaticQueries } from '../src/build/queries';
import type { ParsedDataModel } from '../src/types/models';
import type { AppRoutes } from '../src/types/routes';
import type { RawQuery, AssocQuery } from '../src/types/queries';
import type { StaticQueries } from '../src/types/static';

const GENERATED_DIR = join(process.cwd(), 'src/generated');
const QUERIES_DIR = join(process.cwd(), 'src/custom/queries');

async function writeGenerated(
  fileName: string,
  typeImport: string,
  typeName: string,
  varName: string,
  value: unknown
): Promise<void> {
  const content = `// AUTO-GENERATED by scripts/generate.ts - do not edit by hand, and do not
// commit (see .gitignore) - it's regenerated from ZENDRO_DATA_MODELS on
// every dev/build via predev/prebuild.
${typeImport}

const ${varName}: ${typeName} = ${JSON.stringify(value)};

export default ${varName};
`;
  const formatted = await format(content, { parser: 'typescript', semi: true, singleQuote: true });
  await mkdir(GENERATED_DIR, { recursive: true });
  await writeFile(join(GENERATED_DIR, fileName), formatted);
}

// Ported from queries.preval.ts's formatQuery - same output shape, so
// nothing that imports an individual generated query file needs to change.
async function formatQueryFile(
  { name, query, resolver, transform }: RawQuery | AssocQuery,
  assocResolver?: string
): Promise<string> {
  const graphqlQuery = await format(query, { parser: 'graphql' });

  const content = `
    import { gql } from 'graphql-request';

    export const name = '${name}';

    export const query = gql\`${graphqlQuery}\`;

    export const resolver = '${resolver}';

    export const transform = ${transform ? "'" + transform + "'" : undefined};

    ${assocResolver ? `export const assocResolver = '${assocResolver}';` : ''}

    export default {
      name,
      query,
      resolver,
      transform,
      ${assocResolver ? 'assocResolver' : ''}
    };
  `;

  return format(content, { parser: 'typescript', semi: true, singleQuote: true, trailingComma: 'es5' });
}

// Writes both the per-query files under src/custom/queries/ (matching the
// original's convention - a reference/override point for hand-authored
// custom queries, not itself read back in here) and the aggregated
// src/generated/queries.ts registry that useZendroClient() actually
// consumes at runtime (zendro.queries[model].readAll etc.).
async function writeQueries(modelQueries: Record<string, StaticQueries>): Promise<void> {
  for (const [model, { withFilter, ...queries }] of Object.entries(modelQueries)) {
    const modelDir = join(QUERIES_DIR, model);
    await mkdir(modelDir, { recursive: true });

    for (const q of Object.values(queries)) {
      await writeFile(join(modelDir, `${q.name}.ts`), await formatQueryFile(q));
    }

    const assocDir = join(modelDir, 'associations');
    await mkdir(assocDir, { recursive: true });

    for (const assocQueries of Object.values(withFilter)) {
      for (const q of Object.values(assocQueries)) {
        await writeFile(join(assocDir, `${q.name}.ts`), await formatQueryFile(q, (q as AssocQuery).assocResolver));
      }
    }
  }
}

async function main(): Promise<void> {
  const dataModels: Record<string, ParsedDataModel> = await parseStaticModels();
  await writeGenerated(
    'models.ts',
    "import type { ParsedDataModel } from '@/types/models';",
    'Record<string, ParsedDataModel>',
    'dataModels',
    dataModels
  );

  const appRoutes: AppRoutes = await getModelNavRoutes();
  await writeGenerated(
    'routes.ts',
    "import type { AppRoutes } from '@/types/routes';",
    'AppRoutes',
    'appRoutes',
    appRoutes
  );

  const modelQueries: Record<string, StaticQueries> = await getStaticQueries();
  await writeGenerated(
    'queries.ts',
    "import type { StaticQueries } from '@/types/static';",
    'Record<string, StaticQueries>',
    'queries',
    modelQueries
  );
  await writeQueries(modelQueries);

  console.log(`Generated ${Object.keys(dataModels).length} model(s) from ZENDRO_DATA_MODELS.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
