const {
  REACT_APP_ZENDRO_API_URL,
  REACT_APP_ZENDRO_GRAPHQL_SERVER_URL,
  REACT_APP_ZENDRO_LOGIN_URL,
  REACT_APP_ZENDRO_EXPORT_URL,
  REACT_APP_ZENDRO_MAX_UPLOAD_SIZE,
  REACT_APP_ZENDRO_MAX_RECORD_LIMIT,
  REACT_APP_ZENDRO_REQUEST_LOGGER,
  REACT_APP_ZENDRO_MAX_DYNAMIC_IMPORT_RETRIES,
} = process.env;

export const GRAPHQL_SERVER_URL =
  REACT_APP_ZENDRO_GRAPHQL_SERVER_URL ??
  REACT_APP_ZENDRO_API_URL?.concat('/graphql') ??
  'http://localhost:3000/graphql';

export const LOGIN_URL =
  REACT_APP_ZENDRO_LOGIN_URL ??
  REACT_APP_ZENDRO_API_URL?.concat('/login') ??
  'http://localhost:3000/login';

export const EXPORT_URL =
  REACT_APP_ZENDRO_EXPORT_URL ??
  REACT_APP_ZENDRO_API_URL?.concat('/export') ??
  'http://localhost:3000/export';

export const MAX_UPLOAD_SIZE = Number(REACT_APP_ZENDRO_MAX_UPLOAD_SIZE ?? 500); // size in MB
export const MAX_RECORD_LIMIT = Number(
  REACT_APP_ZENDRO_MAX_RECORD_LIMIT ?? 10000
);
export const REQUEST_LOGGER = REACT_APP_ZENDRO_REQUEST_LOGGER ?? true; // TODO: review this statement
export const MAX_DYNAMIC_IMPORT_RETRIES = Number(
  REACT_APP_ZENDRO_MAX_DYNAMIC_IMPORT_RETRIES ?? 10
);

const config = {
  PORT: 8080,
  GRAPHQL_SERVER_URL,
  LOGIN_URL,
  EXPORT_URL,
  MAX_UPLOAD_SIZE,
  MAX_RECORD_LIMIT,
  REQUEST_LOGGER,
  MAX_DYNAMIC_IMPORT_RETRIES,
};

export default config;
